-- Etihad Engineering Technical Training - OJE Trainee Management
-- Complete Supabase PostgreSQL Schema

-- 1. Batches Table
CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TEXT NOT NULL
);

-- 2. Trainees Table
CREATE TABLE IF NOT EXISTS trainees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    batch_id TEXT NOT NULL,
    program TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TEXT NOT NULL
);

-- 3. Users Table (Authentication)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('MASTER', 'TRAINEE')),
    trainee_id TEXT,
    active BOOLEAN DEFAULT TRUE,
    force_password_change BOOLEAN DEFAULT FALSE,
    last_login TEXT,
    last_password_change TEXT
);

-- 4. Remarks Table
CREATE TABLE IF NOT EXISTS remarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    remark TEXT NOT NULL,
    created_by TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL
);

-- 5. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    date TEXT NOT NULL,
    login_time TEXT NOT NULL,
    status TEXT NOT NULL,
    authentication_method TEXT NOT NULL,
    created_at TEXT NOT NULL,
    CONSTRAINT unique_trainee_date_att UNIQUE (trainee_id, date)
);

-- 6. Allocations Table
CREATE TABLE IF NOT EXISTS allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    location TEXT NOT NULL,
    inside_outside TEXT NOT NULL,
    aircraft_registration TEXT NOT NULL,
    aircraft_type TEXT NOT NULL,
    manager TEXT NOT NULL,
    engineer TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL
);

-- 7. Task Counts Table
CREATE TABLE IF NOT EXISTS task_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    task_count INT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL
);

-- 8. Daily Sign-Outs Table
CREATE TABLE IF NOT EXISTS sign_outs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    date TEXT NOT NULL,
    sign_out_time TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    CONSTRAINT unique_trainee_date_signout UNIQUE (trainee_id, date)
);

-- 9. Passkey Credentials Table
CREATE TABLE IF NOT EXISTS passkey_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id TEXT NOT NULL,
    credential_id TEXT UNIQUE NOT NULL,
    public_key TEXT NOT NULL,
    counter INT DEFAULT 1,
    device_name TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- 10. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    action TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    related_trainee TEXT,
    timestamp BIGINT NOT NULL
);

-- Disable Row Level Security (RLS) policies for direct client access
ALTER TABLE batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE trainees DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE remarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE allocations DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_counts DISABLE ROW LEVEL SECURITY;
ALTER TABLE sign_outs DISABLE ROW LEVEL SECURITY;
ALTER TABLE passkey_credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

-- Seed Default Master User & Batches
INSERT INTO users (username, password_hash, role, active, force_password_change, last_login, last_password_change)
VALUES ('selva.master', 'a8ccb16065696b1a358a36c62a6786e688637ea9be96e3bbf86293e81966dac4', 'MASTER', true, false, null, '2026-09-22')
ON CONFLICT (username) DO NOTHING;

INSERT INTO batches (name, created_at) VALUES ('Batch 1', '2026-09-22') ON CONFLICT (name) DO NOTHING;
INSERT INTO batches (name, created_at) VALUES ('Batch 2', '2026-09-22') ON CONFLICT (name) DO NOTHING;
INSERT INTO batches (name, created_at) VALUES ('OJE Batch 5', '2026-09-22') ON CONFLICT (name) DO NOTHING;
